In [1]:
import sys
import os
import glob
import pandas as pd
import numpy as np
from nilearn import image
sys.path.append('..')
from utils.data import load_participant_list

# Parameters

In [2]:
statistic = 'z_score'
multiple_comp_corr = 'fdr'
alpha = 0.05
run = 'test'

In [3]:
base_dir = '/Users/hugofluhr/data/LH_dev'

dev_sub_ids = ['01', '02', '03', '04', '05', '06']
all_sub_ids = load_participant_list(base_dir)

sub_ids = dev_sub_ids

# Load Model 1 data

In [9]:
first_level_dir = '/Users/hugofluhr/data/LH_dev/nilearn/first_level_scrubbed_demeaned_basic_motion'

contrast_modulator_RL_paths = [
    glob.glob(os.path.join(first_level_dir, f"sub-{sub_id}_run-{run}_model_rl*_z_map.nii.gz"))[0]
    for sub_id in sub_ids
]
contrast_modulator_CK_paths = [
    glob.glob(os.path.join(first_level_dir, f"sub-{sub_id}_run-{run}_model_ck*_z_map.nii.gz"))[0]
    for sub_id in sub_ids
]

contrast_modulator_RL_paths.sort()
contrast_modulator_CK_paths.sort()

In [6]:
contrast_modulator_RL_imgs = [image.load_img(path) for path in contrast_modulator_RL_paths]
contrast_modulator_CK_imgs = [image.load_img(path) for path in contrast_modulator_CK_paths]

# Load Model 2 betamaps data

In [22]:
first_level_dir = '/Users/hugofluhr/data/LH_dev/nilearn/new_first_level_scrubbed_demeaned_basic_motion_with_contrast'

betamap_modulator_RL_paths_2 = [
    glob.glob(os.path.join(first_level_dir, f"sub-{sub_id}_run-{run}_model_rl*masked_z_map.nii.gz"))[0]
    for sub_id in sub_ids
]
betamap_modulator_CK_paths_2 = [
    glob.glob(os.path.join(first_level_dir, f"sub-{sub_id}_run-{run}_model_ck*masked_z_map.nii.gz"))[0]
    for sub_id in sub_ids
]

betamap_modulator_RL_paths_2.sort()
betamap_modulator_CK_paths_2.sort()

In [24]:
betamap_modulator_RL_imgs_2 = [image.load_img(path) for path in betamap_modulator_RL_paths_2]
betamap_modulator_CK_imgs_2 = [image.load_img(path) for path in betamap_modulator_CK_paths_2]

# Compare 
### Model 1 "betamaps" with Model 2 betamaps

In [34]:
i = 5
np.corrcoef(contrast_modulator_CK_imgs[i].get_fdata().flatten(), betamap_modulator_CK_imgs_2[i].get_fdata().flatten())

array([[1.        , 0.53251156],
       [0.53251156, 1.        ]])

### Compare RL and CK effects

In [42]:
i=2
np.corrcoef(betamap_modulator_RL_imgs_2[i].get_fdata().flatten(), betamap_modulator_CK_imgs_2[i].get_fdata().flatten())


array([[1.        , 0.69951974],
       [0.69951974, 1.        ]])

# Load Model 2 CONTRAST data

In [16]:
first_level_dir = '/Users/hugofluhr/data/LH_dev/nilearn/new_first_level_scrubbed_demeaned_basic_motion_with_contrast'

contrast_modulator_RL_paths_2 = [
    glob.glob(os.path.join(first_level_dir, f"sub-{sub_id}_run-{run}_model_rl*contrast_z_map.nii.gz"))[0]
    for sub_id in sub_ids
]
contrast_modulator_CK_paths_2 = [
    glob.glob(os.path.join(first_level_dir, f"sub-{sub_id}_run-{run}_model_ck*contrast_z_map.nii.gz"))[0]
    for sub_id in sub_ids
]

contrast_modulator_RL_paths_2.sort()
contrast_modulator_CK_paths_2.sort()

In [20]:
contrast_modulator_RL_imgs_2 = [image.load_img(path) for path in contrast_modulator_RL_paths_2]
contrast_modulator_CK_imgs_2 = [image.load_img(path) for path in contrast_modulator_CK_paths_2]

# Compare 
### Model 1 "betamaps" with Model 2 contrasts (modulator - unmodulated)

In [21]:
np.corrcoef(contrast_modulator_RL_imgs[0].get_fdata().flatten(), contrast_modulator_RL_imgs_2[0].get_fdata().flatten())

array([[1., 1.],
       [1., 1.]])